figure(1);
subplot(2, 1, 1);
plot(out.Uprav(:,1), out.Uprav(:,2));
title('Управление');
xlabel('Время, с');
ylabel('\phi, deg.');
subplot(2, 1, 2);
plot(out.Povorot(:,1), out.Povorot(:,2));
title('Поворот');
xlabel('Время, с');
ylabel('\delta, deg.');
figure(1);
subplot(2, 1, 1);
plot(out.Uprav(:,1), out.Uprav(:,2));
title('Управление');
xlabel('Время, с');
ylabel('\phi, deg.');
subplot(2, 1, 2);
plot(out.Povorot(:,1), out.Povorot(:,2));
title('Поворот');
xlabel('Время, с');
ylabel('\delta, deg.');